# Generated by Django 5.1 on 2024-08-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawl", "0005_alter_drinklog_portions_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drinklog",
            name="portions",
            field=models.IntegerField(),
        ),
    ]
