# Generated by Django 5.1 on 2024-08-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawl", "0006_alter_drinklog_portions"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="display_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
