# Generated by Django 5.1 on 2024-08-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawl", "0007_profile_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
