# Generated by Django 5.1 on 2024-08-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawl", "0008_alter_profile_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bar",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bar",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
