# Generated by Django 5.1 on 2024-08-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawl", "0009_bar_latitude_bar_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="content",
            field=models.TextField(max_length=200),
        ),
    ]
